### ISSUE TITLE
Question about "Other CMS Integrations"

### ISSUE THREAD

**Issue by Potherca** [ylebre/simply-edit#2]
[We](https://github.com/itmundi) were thinking of trying to write a "connector" for `simply-edit` for another system (or WordPress or whatever) and we couldn't find any instructions in the documentation other than

> CMS Integrations
> 
> We are looking for developers that want to help us integrate the Vedor editor into various platforms. We have integrated the editor in Ariadne, our own web application platform, but the world of the web is a much larger place. Since the editor is now totally decoupled from Ariadne, we want to share it with as many users as possible.

which doesn't really state any follow-up action...

Hence this ticket... How do we _do_?

**Comment by ylebre** [comment]
Updated the text and added a page with more information: http://ylebre.github.io/simply-edit/cms-integration.html
