### ISSUE TITLE
Question: "Custom" backend

### ISSUE THREAD

**Issue by Potherca** [ylebre/simply-edit#3]
Am I correct in thinking that all that is needed to create a "custom" backend for this is an API-key from you guys and handle data from/to the URL `http://example.com/data/data.json` on my own system?

**Comment by ylebre** [comment]
Yes. The default storage layer:
- Loads data.json from <endpoint>data.json;
- Saves data.json to <endpoint>data.json using a PUT request
- Lists files and images using the Apache file index, or a page with links to directories and files.
- Uses the locations in data.json for the sitemap dialog.

More information about custom storage layers is online now: http://ylebre.github.io/simply-edit/cms-integration.html

**Comment by Potherca** [comment]
:+1: Thanks!
